apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./devops/kubernetes/flux/examples/01/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
