apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/olm/"
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: flux-system
  prune: true
  wait: true
