apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/minio/olm/"
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: flux-system
  prune: true
  dependsOn:
    - name: olm
  wait: true
