apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-db-secret
  namespace: keycloak
stringData:
  POSTGRES_DATABASE: keycloak
  POSTGRES_EXTERNAL_ADDRESS: postgresql.postgresql.svc.cluster.local
  POSTGRES_EXTERNAL_PORT: "5432"
  POSTGRES_PASSWORD: keycloak
  # Required for AWS Backup functionality
  POSTGRES_SUPERUSER: "true"
  POSTGRES_USERNAME: keycloak
