apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- postgresql.yaml
- keycloak-operator-group.yaml
- keycloak-subscription.yaml
- keycloak-db-secret.yaml
- keycloak.yaml
